// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtdkbrakyeyprgdyzzfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZGticmFreWV5cHJnZHl6emZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTgwNzksImV4cCI6MjA2MTE3NDA3OX0.lJ1KqKnaMM27Pg6KH98XzQtUB8rcibZx_aFXYA792Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);